development:
  adapter: postgresql
  database: ember-github_development
  pool: 25
  timeout: 5000

test:
  adapter: postgresql
  database: ember-github_test
  pool: 25
  timeout: 5000

production:
  adapter: postgresql
  database: ember-github_production
  pool: 25
  timeout: 5000

